name: Node.js CI

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [12.x, 14.x, 16.x]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test

      - name: Close PR on test failure
        if: failure()
        uses: actions/github-script@0.2.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const ref = context.payload.pull_request.head.ref;
            const prNumber = context.payload.pull_request.number;
            const { owner, repo } = context.repo;

            // Create a review with a request to change
            await github.pulls.createReview({
              owner,
              repo,
              pull_number: prNumber,
              body: 'Test failed. Closing the pull request.',
              event: 'REQUEST_CHANGES'
            });

            // Close the pull request
            await github.pulls.update({
              owner,
              repo,
              pull_number: prNumber,
              state: 'closed'
            });
